<?php 

    return [
        'LAPUYAN' =>[
            'brgy' => [
                "Aludas",
                "Angga an",	
                "Tangkulan", 
                "Kinapat",
                "Kiraon",
                "Kitingting",
                "Lagandang",
                "Macapari",
                "Maican",
                "Migcawayan",
                "New Compostela",
                "Old Damulog",
                "Omonay",
                "Poblacion",
                "Pocopoco",
                "Sampagar",
                "San Isidro"
            ]
        ],
        'MARGOSATUBIG' => [
            'brgy' => [
                "Balintawak",
                "Bularong",
                "Digon",
                "Guinimanan",
                "Igat Island",
                "Josefina","Kalian",
                "San Roque",
                "Limamawan",
                "Limbatong",
                "Lumbog",
                "Magahis",
                "Poblacion",
                "Sagua",
                "Talanusa",
                "Tiguian",
                "Tulapok"
            ]
        ],
        'BAYOG' => [
            'brgy' =>[
                "Baking",
                "Balukbahan",
                "Balumbunan",
                "Bantal",
                "Bobuan",
                "Camp Blessing",
                "Canoayan",
                "Conacon",
                "Dagum",
                "Damit",
                "Datagan",
                "Depase",
                "Dipili",
                "Depore",
                "Deporehan",
                "Dimalinao",
                "Kahayagan",
                "Kanipaan",
                "Lamare",
                "Liba",
                "Matin ao",
                "Matun og",
                "San Isidro",
                "Poblacion",
                "Pulang Bato",
                "Salawagan",
                "Sigacad",
                "Supon",
            ]
        ],
        'TUKURAN' => [
            'brgy' => [
                "Alindahaw",
                "Baclay",
                "Balimbingan",
                "Buenasuerte",
                "Camanga",
                "Curvada",
                "Laperian",
                "Libertad",
                "Lower Bayao",
                "Luy a",
                "Manilan",
                "Manlayag",
                "Militar",
                "Navalan",
                "Panduma Senior",
                "Sambulawan",
                "San Antonio",
                "San Carlos",
                "Santo Niño",
                "Santo Rosario",
                "Sugod",
                "Tabuan",
                "Tagulo",
                "Tinotungan",
                "Upper Bayao"
            ]
        ],
        'AURORA' => [
            'brgy' => ['Acad', 
            'Alang-alang', 
            'Alegria', 
            'Anonang',
            'Bagong Mandaue', 
            'Bagong Maslog',
            'Bagong Oslob', 
            'Bagong Pitogo', 
            'Baki', 
            'Balas', 
            'Balide', 
            'Balintawak', 
            'Bayabas', 
            'Bemposa',
            'Cabilinan', 
            'Campo Uno', 
            'Ceboneg', 
            'Commonwealth', 
            'Gubaan', 
            'Inasagan', 
            'Inroad', 
            'Kahayagan East',
            'Kahayagan West', 
            'Kauswagan', 
            'La Paz', 
            'La Victoria', 
            'Lantungan', 
            'Libertad', 
            'Lintugop', 
            'Lubid', 
            'Maguikay',
            'Mahayahay', 
            'Monte Alegre', 
            'Montela', 
            'Napo', 
            'Panaghiusa', 
            'Poblacion', 
            'Resthouse',
            'Romarate', 
            'San Jose', 
            'San Juan', 
            'Sapa Loboc', 
            'Tagulalo', 
            'Waterfall'
            ]
        ],

        'DIMATALING' => [
            'brgy' => [
                'Bacayawan',
                'Baha',
                'Balanagan',
                'Baluno',
                'Binuay',
                'Buburay',
                'Grap',
                'Josefina',
                'Kagawasan',
                'Lalab',
                'Libertad',
                'Magahis',
                'Mahayag',
                'Mercedes',
                'Poblacion',
                'Saloagan',
                'San Roque',
                'Sugbay Uno',
                'Sumbato',
                'Sumpot',
                'Tinggabulong',
                'Tiniguangan',
                'Tipangi',
                'Upper Ludiong'
            ]
        ],
        'DINAS' => [
            'brgy' => [
                'Bacawan',
                'Benuatan',
                'Beray',
                'Don Jose',
                'Dongos',
                'East Migpulao',
                'Guinicolalay',
                'Ignacio Garrata',
                'Kinakap',
                'Legarda 1',
                'Legarda 2',
                'Legarda 3',
                'Lower Dimaya',
                'Locuban',
                'Ludiong',
                'Nangka',
                'Nian',
                'Old Mirapao',
                'Pisa an',
                'Poblacion',
                'Proper Dimaya',
                'Sagacad',
                'Sambulawan',
                'San Isidro',
                'Sungayan',
                'Sumpotan',
                'Tarakan',
                'Upper Dimaya',
                'Upper Sibul',
                'West Migpulao'
            ]
        ],
        'DUMALINAO' => [
            'brgy' => [
                'Anonang',
                'Bagong Misamis',
                'Bag ong Silao',
                'Baga',
                'Baloboan',
                'Banta ao',
                'Bibilik',
                'Calingayan',
                'Camalig',
                'Camanga',
                'Cuatro cuatro',
                'Locuban',
                'Malasik',
                'Mama',
                'Matab ang',
                'Mecolong',
                'Metokong',
                'Motosawa',
                'Pag asa',
                'Paglaum',
                'Pantad',
                'Piniglibano',
                'Rebokon',
                'San Agustin',
                'Sebucao',
                'Sumadat',
                'Tikwas',
                'Tina',
                'Tubo Pait',
                'Upper Dumalinao'
            ]
        ],
        'DUMINGAG'=> [
            'brgy' => [
                'Bagong Valencia',
                'Bagong Kauswagan',
                'Bagong Silangan',
                'Bucayan',
                'Calumanggi',
                'Canibongan',
                'Caridad',
                'Danlugan',
                'Dapiwak',
                'Datu Totoca',
                'Dilud',
                'Ditulan',
                'Dulian',
                'Dulop',
                'Guintananan',
                'Guitran',
                'Gumpingan',
                'La Fortuna',
                'Labangon',
                'Libertad',
                'Licabang',
                'Lipawan',
                'Lower Landing',
                'Lower Timonan',
                'Macasing',
                'Mahayahay',
                'Malagalad',
                'Maralag',
                'Marangan',
                'New Basak',
                'Saad',
                'Salvador',
                'San Juan',
                'San Pablo',
                'San Pedro',
                'San Vicente',
                'Senote',
                'Sinonok',
                'Sunop',
                'Tagun',
                'Tamurayan',
                'Upper Landing',
                'Upper Timonan'
            ]
        ],
        'GUIPOS'=> [
            'brgy' => [
                'Bagong Oroquieta',
                'Baguitan',
                'Balongating',
                'Canunan',
                'Dacsol',
                'Dagohoy',
                'Dalapang',
                'Datagan',
                'Guling',
                'Katipunan',
                'Lintum',
                'Litan',
                'Magting',
                'Poblacion',
                'Regla',
                'Sikatuna',
                'Singclot'
            ]
        ],
        'JOSEFINA'=> [
            'brgy' => [
                'Bogo Calabat',
                'Dawa',
                'Ebarle',
                'Gumahan',
                'Leonardo',
                'Litapan',
                'Lower Bagong Tudela',
                'Mansanas',
                'Moradji',
                'Nemeño',
                'Nopulan',
                'Sebukang',
                'Tagaytay Hill',
                'Upper Bagong Tudela'
            ]
        ],
        'KUMALARANG'=> [
            'brgy' => [
                'Bogayo',
                'Bolisong',
                'Boyugan East',
                'Boyugan West',
                'Bualan',
                'Diplo',
                'Gawil',
                'Gusom',
                'Kitaan Dagat',
                'Lantawan',
                'Limamawand',
                'Mahayahay',
                'Pangi',
                'Picanan',
                'Poblacion',
                'Salagmanok',
                'Secade',
                'Suminalum'
            ]
        ],
        'LABANGAN'=> [
            'brgy' => [
                'Bagalupa',
                'Balimbingan',
                'Binayan',
                'Bokong',
                'Bulanit',
                'Cogonan',
                'Combo',
                'Dalapang',
                'Dimasangca',
                'Dipaya',
                'Langapod',
                'Lantian',
                'Lower Campo Islam',
                'Lower Pulacan',
                'Lower Sang-an',
                'New Labangan',
                'Noboran',
                'Old Labangan',
                'San Isidro',
                'Santa Cruz',
                'Tapodoc',
                'Tawagan Norte',
                'Upper Campo Islam',
                'Upper Pulacan',
                'Upper Sang-an'
            ]
        ],
        'LAKEWOOD'=> [
            'brgy' => [
                'Bagong Kahayag',
                'Baking',
                'Biswangan',
                'Bululawan',
                'Dagum',
                'Gasa',
                'Gatub',
                'Lukuan',
                'Matalang',
                'Poblacion',
                'Sapang Pinoles',
                'Sebuguey',
                'Tiwales',
                'Tubod'
            ]
        ],
        'MAHAYAG'=> [
            'brgy' => [
                'Bagong Balamban',
                'Bagong Dalaguete',
                'Boniao',
                'Delusom',
                'Diwan',
                'Guripan',
                'Kaangayan',
                'Kabuhi',
                'Lourmah',
                'Lower Salug Daku',
                'Lower Santo Nino',
                'Malubo',
                'Manguiles',
                'Marabanan',
                'Panagaan',
                'Paraiso',
                'Pedagan',
                'Pugwan',
                'Poblacion',
                'San Isidro',
                'San Jose',
                'San Vicente',
                'Santa Cruz',
                'Sicpao',
                'Tuboran',
                'Tulan',
                'Tumapic',
                'Upper Salug Daku',
                'Upper Santo Nino'
            ]
        ], 
        'MIDSALIP'=> [
            'brgy' => [
                'Bacahan',
                'Balonai',
                'Bibilop',
                'Buloron',
                'Cabaloran',
                'Canipay Norte',
                'Canipay Sur',
                'Cumarom',
                'Dakayakan',
                'Duelic',
                'Dumalinao',
                'Ecuan',
                'Golictop',
                'Guinabot',
                'Guitalos',
                'Guma',
                'Kahayagan',
                'Licuro-an',
                'Lumpunid',
                'Matalang',
                'New Katipunan',
                'New Unidos',
                'Palili',
                'Pawan',
                'Pili',
                'Pisompongan',
                'Piwan',
                'Poblacion A',
                'Poblacion B',
                'Sigapod',
                'Timbaboy',
                'Tulbong',
                'Tuluan'
            ]
        ],
        'MOLAVE'=> [
            'brgy' => [
                'Alicia',
                'Ariosa',
                'Bagong Argao',
                'Bagong Gutlang',
                'Blancia',
                'Bogo Capalaran',
                'Culo',
                'Dalaon',
                'Dipolo',
                'Dontulan',
                'Gonosan',
                'Lower Dimalinao',
                'Pablo Bahinting Sr',
                'Mabuhay',
                'Madasigon',
                'Makuguihon',
                'Maloloy on',
                'Miligan',
                'Parasan',
                'Rizal',
                'Santo Rosario',
                'Silangit',
                'Simata',
                'Sudlon',
                'Upper Dimorok'
            ]
        ],
        'PITOGO'=> [
            'brgy' => [
                'Balabawan',
                'Balong balong',
                'Colojo',
                'Liasan',
                'Liguac',
                'Limbayan',
                'Lower Paniki an',
                'Matin-ao',
                'Panubigan',
                'Poblacion',
                'Punta Flecha',
                'Sugbay Dos',
                'Tongao',
                'Upper Paniki an',
                'San Isidro'
            ]
        ],
        'RAMONMAGSAYSAY'=> [
            'brgy' => [
                'Bagong Opon',
                'Bambong Daku',
                'Bambong Diut',
                'Bobongan',
                'Campo IV',
                'Campo V',
                'Caniangan',
                'Dipalusan',
                'Eastern Bobongan',
                'Esperanza',
                'Gapasan',
                'Katipunan',
                'Kauswagan',
                'Lower Sambulawan',
                'Mabini',
                'Magsaysay',
                'Malating',
                'Paradise',
                'Pasingkalan',
                'Poblacion',
                'San Fernando',
                'Santo Rosario',
                'Sapa Anding',
                'Sinaguing',
                'Switch',
                'Upper Laperian',
                'Wakat'
            ]
        ],
        'SANMIGUEL'=> [
            'brgy' => [
                'Betinan',
                'Bulawan',
                'Calube',
                'Concepcion',
                'Dao an',
                'Dumalian',
                'Fatima',
                'Langilan',
                'Lantawan',
                'Laperian',
                'Libuganan',
                'Limonan',
                'Mati',
                'Ocapan',
                'Poblacion',
                'San Isidro',
                'Sayog',
                'Tapian'
            ]
        ],
        'SANPABLO'=> [
            'brgy' => [
                'Bagong Misamis',
                'Bubual',
                'Buton',
                'Culasian',
                'Daplayan',
                'Kalilangan',
                'Kapamanok',
                'Kondum',
                'Lumbayao',
                'Mabuhay',
                'Marcos Village',
                'Miasin',
                'Molansong',
                'Pantad',
                'Pao',
                'Payag',
                'Poblacion',
                'Pongapong',
                'Sacbulan',
                'Sagasan',
                'San Juan',
                'Senior',
                'Songgoy',
                'Tandubuay',
                'Taniapan',
                'Ticala Island',
                'Tubo pait',
                'Villakapa'
            ]
        ],
        'SOMINOT'=> [
            'brgy' => [
                'Bag ong Baroy',
                'New Oroquieta',
                'Barubuhan',
                'Bulanay',
                'Datagan',
                'Eastern Poblacion',
                'Lantawan',
                'Libertad',
                'Lumangoy',
                'New Carmen',
                'Picturan',
                'Poblacion',
                'Rizal',
                'San Miguel',
                'Santo Niño',
                'Sawa',
                'Tungawan',
                'Upper Sicpao'
            ]
        ],
        'TABINA'=> [
            'brgy' => [
                'Abong abong',
                'Baganian',
                'Baya-baya',
                'Capisan',
                'Concepcion',
                'Culabay',
                'Doña Josefina',
                'Lumbia',
                'Mabuhay',
                'Malim',
                'Manicaan',
                'New Oroquieta',
                'Poblacion',
                'San Francisco',
                'Tultolan'
            ]
        ],
        'TAMBULIG'=> [
            'brgy' => [
                'Alang alang',
                'Angeles',
                'Bagong Kauswagan',
                'Bagong Tabogon',
                'Balugo',
                'Cabgan',
                'Calolot',
                'Dimalinao',
                'Fabian',
                'Gabunon',
                'Happy Valley',
                'Kapalaran',
                'Libato',
                'Limamaan',
                'Lower Liasan',
                'Lower Lodiong',
                'Lower Tiparak',
                'Lower Usogan',
                'Maya maya',
                'New Village,',
                'Pelocuban',
                'Riverside',
                'Sagrada Familia',
                'San Jose',
                'San Vicente',
                'Sumalig',
                'Tuluan',
                'Tungawan',
                'Upper Liaison',
                'Upper Lodiong',
                'Upper Tiparak'
            ]
        ],
        'TIGBAO'=> [
            'brgy' => [
            'Begong',
            'Busol',
            'Caluma',
            'Diana Countryside',
            'Guinlin',
            'Lacarayan',
            'Lacupayan',
            'Libayoy',
            'Limas',
            'Longmot',
            'Maragang',
            'Mati',
            'Nangan nangan',
            'New Tuburan',
            'Nilo',
            'Tigbao',
            'Timolan',
            'Upper Nilo'
            ]
        ],
        'VINCENZOSAGUN'=> [
            'brgy' => [
                'Ambulon',
                'Biu os',
                'Cogon',
                'Danan',
                'Kabatan',
                'Kapatagan',
                'Limason',
                'Linoguayan',
                'Lumbal',
                'Lunib',
                'Maculay',
                'Maraya',
                'Sagucan',
                'Waling waling'
            ]
        ]
];